name: Python Tests

on:
  pull_request:  # Run this workflow for pull requests
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black  # Add these if not already in requirements.txt

      # Step 4: Run tests
      - name: Run unittest
        run: python -m unittest discover -s tests

      # Step 5: Check code formatting
      - name: Run Ruff
        run: ruff check . --fix

      # Step 6: Check code style with black
      - name: Check code formatting with Black
        run: black --check .
